### ISSUE TITLE
Better exceptions not working in 3.13?

### ISSUE THREAD

**Issue by xl0** [Qix-/better-exceptions#134]
```
$ python --version
Python 3.13.0
```

```python
import better_exceptions
better_exceptions.hook()

def f(x):
    return x/0

f(1)
```

```
$ python test.py 
Traceback (most recent call last):
  File "/home/xl0/work/projects/lovely-tensors/test.py", line 8, in <module>
    f(1)
  File "/home/xl0/work/projects/lovely-tensors/test.py", line 6, in f
    return x/0
ZeroDivisionError: division by zero
```

Works with 3.12:
```
$ python --version
Python 3.12.7
```

```
$ python test.py 
Traceback (most recent call last):
  File "/home/xl0/work/projects/lovely-tensors/test.py", line 8, in <module>
    f(1)
    └ <function f at 0x7bbba181d760>
  File "/home/xl0/work/projects/lovely-tensors/test.py", line 6, in f
    return x/0
           └ 1
ZeroDivisionError: division by zero
```

**Comment by xl0** [comment]
This is due to a silent change in how traceback.format_list behaves:

`demo_format_list_change.py:`
```py
import traceback
import sys

print(f"Python {sys.version_info.major}.{sys.version_info.minor}")

# Frame with multiline text (source + variable annotations)
frames = [('test.py', 10, 'func', 'x = foo + bar\n\t\thello\n\tworld')]

print("\nInput (3 lines):")
print(repr(frames[0][3]))

print("\nOutput from traceback.format_list():")
result = traceback.format_list(frames)[0] # Yes, it't always a 1-element list both on 3.12 adn 3.13.
print(result)
```

`$ python3.12 demo_format_list_change.py`
```
Python 3.12

Input (3 lines):
'x = foo + bar\n\t\thello\n\tworld'

Output from traceback.format_list():
  File "test.py", line 10, in func
    x = foo + bar
                hello
        world
```

`python3.13 demo_format_list_change.py`

```
Python 3.13

Input (3 lines):
'x = foo + bar\n\t\thello\n\tworld'

Output from traceback.format_list():
  File "test.py", line 10, in func
    x = foo + bar
```


It only shows the first line! 

While this is annoying and python is at fault, I think we should just format it manually regardless of version:
```
--- a/better_exceptions/formatter.py
+++ b/better_exceptions/formatter.py
@@ -282,7 +282,12 @@ class ExceptionFormatter(object):
 
             tb = tb.tb_next
 
-        lines = traceback.format_list(frames)
+        # Format frames manually instead of using traceback.format_list()
+        # Python 3.13+ changed format_list() to only show the first line of multiline text
+        lines = []
+        for filename, lineno, name, text in frames:
+            lines.append('  File "{}", line {}, in {}\n'.format(filename, lineno, name))
+            lines.append('    {}\n'.format(text))
 
         return ''.join(lines), final_source
```
