### ISSUE TITLE
Add support for doc strings in functions

### ISSUE THREAD

**Issue by RootLUG** [Qix-/better-exceptions#25]
It might be helpful to have an option to enable showing doc string in traceback if the function has it defined in `__doc__` attribute near the traceback explanation section to make it even more awesome

**Comment by Qix-** [comment]
Sure, should be do-able. I'll see how it looks.

**Comment by Qix-** [comment]
Could you try with the following?

```
pip install https://github.com/qix-/better-exceptions/archive/add-docstrings.tar.gz
```

**Comment by RootLUG** [comment]
I tried it by passing a function as an argument to other function (which case exception as it accept only string) where both functions have docstring defined:

```
Traceback (most recent call last):
  File "blah.py", line 13, in <module>
    func1(func2)
    │     └ <function load_whois at 0x7f1a60fdade8>
    └ <bound method type.get_ns of <class 'someproject.dns.Domain'>>
  File "dns.py", line 413, in get_ns
    domain_parts = cls.split(domain, full=True)
                   │         └ <function load_whois at 0x7f1a60fdade8>
                   └ <class 'someproject.dns.Domain'>
  File "dns.py", line 366, in split
    if domain.endswith("." + line) and (largest_suffix is None or len(largest_suffix) < len(line)):
AttributeError: 'function' object has no attribute 'endswith'

```

It displayed it without the dosctring even if the same test script I can access the docstring by using print(func1.__doc__)
Here's the snippet I used:

```
import better_exceptions
import someproject

func1 = someproject.Domain.get_ns
func2 = someproject.load_whois
# print(func1.__doc__)
func1(func2)
```

I also noticed when I use functions/variables like `someproject.Domain.get_ns` the better_exceptions is displaying the information about the `someproject` module rather then descending down to the function `get_ns` in `someproject.Domain.get_ns`. May that be the case why it didn't displayed the docstring? I changed the example above to assign those testing functions directly to `func1` and `func2` but that didn't helped

**Comment by RootLUG** [comment]
I just tested that a localy defined function works well if it's not imported from other module

The docstring might need to be re-intended if it's multiline as it's lightly off like this, but that's just a small cosmetic issue:

```
  File "blah.py", line 10, in some_other_func
    """
        This is just for testing
        """
    a(b)
.... rest of the traceback
```

**Comment by Qix-** [comment]
Oh I forgot to strip, thanks for reminding me.

Strange about imported members. I'll investigate!

**Comment by RootLUG** [comment]
Small update, I noticed that for normally installed modules the docstring in traceback is correctly shown. My module which has docstrings but are not shown in traceback is installed via setup.py using the develop option. That might be related to the issue but I haven't been able to confirm

**Comment by Qix-** [comment]
@RootLUG Could you explain what you mean? What's the develop option? (I'm not completely well versed in setup.py affairs).

**Comment by RootLUG** [comment]
Sure, normally the python package is installed by setup.py install, by using this python copies the package into it's site-packages directory. That's a little bit pitty if you want to do some modifications to the package (e.g. you are a developer), then you need to reinstall it each time to reflect the changes. Hence the option 'develop' for setup.py which will install the package by creating a cross-platform symlink instead of copying the package so you can make changes to the installed package as you wish and it will be immediately reflected

The package where the doc strings were missing has been installed using this method which may be related to the observed bug.

**Comment by Qix-** [comment]
Interesting, I see.

I know this might be a lot to ask but could you post some code and a setup.py that could reproduce this?

**Comment by ArneBachmann** [comment]
I think what @RootLUG  might mean is something like `pip install -e .` which only creates a link to the current directory in the Python distribution instead of copying all built files there (a.k.a. editable install). RIght?

**Comment by RootLUG** [comment]
Hello, sorry for a long delay, I kind of forgotten about it.
I think the issue as originally reported was for a package that was installed via command `python setup.py develop` so it was an editable local egg, should be the same as `pip install -e` @ArneBachmann . I no longer have the original source code around for which I reported the issue but I can give it a try for some other projects which I have installed like this and also have docstrings.
