### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by readylan** [Qix-/better-exceptions#26]
While working with virtualenv, I get this error:

```
Python 2.7.12 (aff251e54385, Nov 09 2016, 18:02:49)
[PyPy 5.6.0 with GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import better_exceptions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/********************/site-packages/better_exceptions/__init__.py", line 49, in <module>
    'builtins': __builtins__.keys(),
AttributeError: 'module' object has no attribute 'keys'
```

**Comment by Qix-** [comment]
This is strange. On the command line, `__builtins__.keys()` errors. With the code, it appears to work fine.

Let me take a look.

**Comment by Qix-** [comment]
Can you test using the latest master?

**Comment by readylan** [comment]
Yes, tested v. 0.1.6 and running. Thanks !
