### ISSUE TITLE
Don't work on termux

### ISSUE THREAD

**Issue by Unviray** [Qix-/better-exceptions#68]
Python version: 3.7.2
better_exceptions: 0.2.2
```
>>> import g
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'g'
>>> import better_exceptions; better_exceptions.hook()
WARNING: better_exceptions will only inspect code from the command line
         when using: `python -m better_exceptions'. Otherwise, only code
         loaded from files will be inspected!
>>> import g
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'g'
>>>
```

**Comment by Qix-** [comment]
The prompt tells you exactly why it's not working...

**Comment by Unviray** [comment]
Yes, but the exception is not better 😁.

**Comment by Qix-** [comment]
I can't help you any further from what the terminal tells you...
